# -*- coding: utf-8 -*-
# @Time    : 2023/10/21 11:02 CST
# @Author  : Guangchen Jiang
# @Email   : guangchen98.jiang@gmail.com
# @File    : configs/evol_config.yaml

judgment threshold: 5
total round: 2000000
burn in time: 500000
population size: 50
error rate: 0.05
observation probability: 0.9
score threshold: 0
selection strength: 1.
reward matrix:
    benefit of cooperation: 5.
    cost of cooperation: 1.