# -*- coding: utf-8 -*-
# @Time    : 2023/10/21 11:02 CST
# @Author  : Guangchen Jiang
# @Email   : guangchen98.jiang@gmail.com
# @File    : src/recovery/config.yaml

total round: 1000
population size: 50
error rate: 0.
observation probability: 1.
score threshold: 0